### ISSUE TITLE
Error: Invalid address to set: []string{"bitbucket_settings", "0", "upgraded_to_v2_hooks"}

### ISSUE THREAD

**Issue by ehamberg** [yougroupteam/terraform-buildkite#3]
I get the following error when I call `terraform plan`:

```
Error: Invalid address to set: []string{"bitbucket_settings", "0", "upgraded_to_v2_hooks"}
```

I attempted to clear the state and re-import the pipeline, but I got the same error.

(The pipeline in question does indeed have a bitbucket repository associated with it.)

**Comment by desmondcheng** [comment]
@ehamberg we don't have bitbucket accounts for testing, but this #4 should fix the issue

please re-import the pipeline and try again

**Comment by ehamberg** [comment]
@desmondcheng Yep. That seems to have fixed it. Thanks!
