### ISSUE TITLE
Build Skipping

### ISSUE THREAD

**Issue by juliangrosshauser** [yougroupteam/terraform-buildkite#5]
The existing [`build-skipping`](https://github.com/yougroupteam/terraform-buildkite/tree/build-skipping) branch works without problems for me. Merging it into `master` also doesn't cause any merge conflicts.

Can we get this branch merged into `master`, or are there any issues I'm not aware of?

**Comment by desmondcheng** [comment]
the branch has already been merged. closing issue.
